import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

const DESIGNER_COLORS = {
  TentDesign: "bg-purple-100 text-purple-800",
  RoomDesigner: "bg-amber-100 text-amber-800",
  OutdoorPlanner: "bg-blue-100 text-blue-800",
};

const IMAGE_TYPE_COLORS = {
  "Option1-Premium": "bg-green-100 text-green-800",
  "Option2-Budget": "bg-orange-100 text-orange-800",
  "3D-Render": "bg-violet-100 text-violet-800",
};

export default function AdminLogs() {
  const [search, setSearch] = useState("");
  const [filterDesigner, setFilterDesigner] = useState("all");

  const { data: logs = [], isLoading } = useQuery({
    queryKey: ["ai-image-logs"],
    queryFn: () => base44.entities.AIImageLog.list("-created_date", 200),
  });

  // Build chart data: last 14 days in 24h intervals
  const chartData = (() => {
    const days = 14;
    const now = new Date();
    return Array.from({ length: days }, (_, i) => {
      const d = new Date(now);
      d.setDate(now.getDate() - (days - 1 - i));
      d.setHours(0, 0, 0, 0);
      const next = new Date(d);
      next.setDate(d.getDate() + 1);
      const label = d.toLocaleDateString([], { month: "short", day: "numeric" });
      const count = logs.filter((log) => {
        const t = new Date(log.created_date).getTime();
        return t >= d.getTime() && t < next.getTime();
      }).length;
      return { date: label, count };
    });
  })();

  const filtered = logs.filter((log) => {
    const matchesSearch =
      !search ||
      (log.project_name || "").toLowerCase().includes(search.toLowerCase()) ||
      (log.prompt_summary || "").toLowerCase().includes(search.toLowerCase());
    const matchesDesigner =
      filterDesigner === "all" || log.designer === filterDesigner;
    return matchesSearch && matchesDesigner;
  });

  return (
    <div className="min-h-screen bg-zinc-950 p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-2">AI Image Logs</h1>
        <p className="text-zinc-400 mb-8">All images generated by AI designers</p>

        {/* Filters */}
        <div className="flex gap-3 mb-6 flex-wrap">
          <Input
            placeholder="Search project or prompt..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="bg-zinc-900 border-zinc-700 text-white max-w-xs"
          />
          <Select value={filterDesigner} onValueChange={setFilterDesigner}>
            <SelectTrigger className="bg-zinc-900 border-zinc-700 text-white w-44">
              <SelectValue placeholder="All Designers" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Designers</SelectItem>
              <SelectItem value="TentDesign">Tent Design</SelectItem>
              <SelectItem value="RoomDesigner">Room Designer</SelectItem>
              <SelectItem value="OutdoorPlanner">Outdoor Planner</SelectItem>
            </SelectContent>
          </Select>
          <span className="text-zinc-500 text-sm self-center">{filtered.length} images</span>
        </div>

        {/* Chart */}
        {!isLoading && logs.length > 0 && (
          <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 mb-8">
            <h2 className="text-white font-semibold mb-4">Images Generated (Last 14 Days)</h2>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={chartData} margin={{ top: 5, right: 10, left: 0, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#3f3f46" />
                <XAxis dataKey="date" tick={{ fill: "#a1a1aa", fontSize: 11 }} />
                <YAxis allowDecimals={false} tick={{ fill: "#a1a1aa", fontSize: 11 }} width={30} />
                <Tooltip
                  contentStyle={{ background: "#18181b", border: "1px solid #3f3f46", color: "#fff", borderRadius: 8 }}
                  labelStyle={{ color: "#f4f4f5" }}
                  cursor={{ fill: "#27272a" }}
                />
                <Bar dataKey="count" fill="#f59e0b" radius={[4, 4, 0, 0]} name="Images" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}

        {isLoading ? (
          <p className="text-zinc-400">Loading...</p>
        ) : filtered.length === 0 ? (
          <p className="text-zinc-500 text-center py-16">No images logged yet. Generate images in the AI designers to see them here.</p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {filtered.map((log) => (
              <div key={log.id} className="bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden">
                <a href={log.image_url} target="_blank" rel="noopener noreferrer">
                  <img
                    src={log.image_url}
                    alt={log.project_name || "AI generated"}
                    className="w-full h-44 object-cover hover:opacity-90 transition-opacity"
                    onError={(e) => { e.target.style.display = 'none'; }}
                  />
                </a>
                <div className="p-3 space-y-2">
                  <div className="flex gap-2 flex-wrap">
                    <Badge className={DESIGNER_COLORS[log.designer] || "bg-zinc-700 text-zinc-300"}>
                      {log.designer || "Unknown"}
                    </Badge>
                    {log.image_type && (
                      <Badge className={IMAGE_TYPE_COLORS[log.image_type] || "bg-zinc-700 text-zinc-300"}>
                        {log.image_type}
                      </Badge>
                    )}
                  </div>
                  {log.project_name && (
                    <p className="text-white text-sm font-medium truncate">{log.project_name}</p>
                  )}
                  {log.prompt_summary && (
                    <p className="text-zinc-500 text-xs line-clamp-2">{log.prompt_summary}</p>
                  )}
                  <p className="text-zinc-600 text-xs">
                    {new Date(log.created_date).toLocaleDateString()} {new Date(log.created_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}